# **Entendimiento y Preparación de los Datos**
---

## **1. Análisis Exploratorio de los Datos**
---

### **1.1. Cargar los datos**
---

A continuación se realiza el cargue de los datos

In [ ]:
# Librarías requeridas
import matplotlib.pyplot as plt
import matplotlib as mpl
import pandas as pd
import numpy as np
import seaborn as sns

In [ ]:

# Cargar el archivo CSV
df = pd.read_csv('arabica_data_cleaned.csv')
df.head(4)

,Unnamed: 0,Species,Owner,Country.of.Origin,Farm.Name,Lot.Number,Mill,ICO.Number,Company,Altitude,...,Color,Category.Two.Defects,Expiration,Certification.Body,Certification.Address,Certification.Contact,unit_of_measurement,altitude_low_meters,altitude_high_meters,altitude_mean_meters
0,1,Arabica,metad plc,Ethiopia,metad plc,NaN,metad plc,2014/2015,metad agricultural developmet plc,1950-2200,...,Green,0,"April 3rd, 2016",METAD Agricultural Development plc,309fcf77415a3661ae83e027f7e5f05dad786e44,19fef5a731de2db57d16da10287413f5f99bc2dd,m,1950.0,2200.0,2075.0
1,2,Arabica,metad plc,Ethiopia,metad plc,NaN,metad plc,2014/2015,metad agricultural developmet plc,1950-2200,...,Green,1,"April 3rd, 2016",METAD Agricultural Development plc,309fcf77415a3661ae83e027f7e5f05dad786e44,19fef5a731de2db57d16da10287413f5f99bc2dd,m,1950.0,2200.0,2075.0
2,3,Arabica,grounds for health admin,Guatemala,"san marcos barrancas ""san cristobal cuch",NaN,NaN,NaN,NaN,1600 - 1800 m,...,NaN,0,"May 31st, 2011",Specialty Coffee Association,36d0d00a3724338ba7937c52a378d085f2172daa,0878a7d4b9d35ddbf0fe2ce69a2062cceb45a660,m,1600.0,1800.0,1700.0
3,4,Arabica,yidnekachew dabessa,Ethiopia,yidnekachew dabessa coffee plantation,NaN,wolensu,NaN,yidnekachew debessa coffee plantation,1800-2200,...,Green,2,"March 25th, 2016",METAD Agricultural Development plc,309fcf77415a3661ae83e027f7e5f05dad786e44,19fef5a731de2db57d16da10287413f5f99bc2dd,m,1800.0,2200.0,2000.0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1311 entries, 0 to 1310
Data columns (total 44 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Unnamed: 0             1311 non-null   int64
 1   Species                1311 non-null   object
 2   Owner                  1304 non-null   object
 3   Country.of.Origin      1310 non-null   object
 4   Farm.Name              955 non-null    object
 5   Lot.Number             270 non-null    object
 6   Mill                   1001 non-null   object
 7   ICO.Number             1163 non-null   object
 8   Company                1102 non-null   object
 9   Altitude               1088 non-null   object
 10  Region                 1254 non-null   object
 11  Producer               1081 non-null   object
 12  Number.of.Bags         1311 non-null   int64
 13  Bag.Weight             1311 non-null   object
 14  In.Country.Partner     1311 non-null   object
 15  Harvest.Year           1264 non-null   object
 16  Grading.Date           1311 non-null   object
 17  Owner.1                1304 non-null   object
 18  Variety                1110 non-null   object
 19  Processing.Method      1159 non-null   object
 20  Aroma                  1311 non-null   float64
 21  Flavor                 1311 non-null   float64
 22  Aftertaste             1311 non-null   float64
 23  Acidity                1311 non-null   float64
 24  Body                   1311 non-null   float64
 25  Balance                1311 non-null   float64
 26  Uniformity             1311 non-null   float64
 27  Clean.Cup              1311 non-null   float64
 28  Sweetness              1311 non-null   float64
 29  Cupper.Points          1311 non-null   float64
 30  Total.Cup.Points       1311 non-null   float64
 31  Moisture               1311 non-null   float64
 32  Category.One.Defects   1311 non-null   int64
 33  Quakers                1310 non-null   float64
 34  Color                  1044 non-null   object
 35  Category.Two.Defects   1311 non-null   int64
 36  Expiration             1311 non-null   object
 37  Certification.Body     1311 non-null   object
 38  Certification.Address  1311 non-null   object
 39  Certification.Contact  1311 non-null   object
 40  unit_of_measurement    1311 non-null   object
 41  altitude_low_meters    1084 non-null   float64
 42  altitude_high_meters   1084 non-null   float64
 43  altitude_mean_meters   1084 non-null   float64
dtypes: float64(16), int64(4), object(24)
memory usage: 450.8+ KB